---
- hosts: all
  become: yes
  vars_files:
  - secrets.yml
  vars:
    mongo_admin_user: bloop
    mongo_database: comics_scrape
    mongo_user: comics_scrape
    postgresql_users:
    - name: comics
      password: "{{ postgres_password }}"
    #postgresql_data_dir: /var/db/postgres/data
    postgresql_databases:
    - name: comics
  roles:
  - { role: geerlingguy.ntp, become: yes }
  - { role: geerlingguy.postgresql, become: yes }
  tasks:
    - name: install packages
      package:
        update_cache: yes
        pkg:
        - nginx
        - mongodb
        - python-setuptools
        - python3
        - python3-pymongo
        - python3-setuptools
        - python3-pip
        - python3-virtualenv
        - virtualenv
        - libev-dev # bjoern dependency
        #- redis

    - name: create mongo root user
      mongodb_user:
        login_port: "27017"
        database: "admin"
        name: "{{ mongo_admin_user }}"
        password: "{{ mongo_admin_password }}"
        roles: "root"

    - name: create mongodb user
      mongodb_user:
        login_user: "{{ mongo_admin_user }}"
        login_password: "{{ mongo_admin_password }}"
        login_port: "27017"
        database: "{{ mongo_database }}"
        name: "{{ mongo_user }}"
        password: "{{ mongo_password }}"
        roles:
          - { db: "admin", role: "readWrite" }
          - { db: "{{ mongo_database }}", role: "readWrite" }
